# Generated by Django 4.1.2 on 2022-10-25 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0003_alter_vehicle_license_plate"),
        ("shifts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shiftvehicle",
            name="shift",
            field=models.ForeignKey(
                help_text="Vehicle is assigned to this shift.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shift_vehicles",
                to="shifts.shift",
                verbose_name="Shift",
            ),
        ),
        migrations.AlterField(
            model_name="shiftvehicle",
            name="vehicle",
            field=models.ForeignKey(
                help_text="Vehicle is assigned to this shift.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shift_vehicles",
                to="vehicles.vehicle",
                verbose_name="Vehicle",
            ),
        ),
    ]
