# Generated by Django 4.1.2 on 2022-10-24 20:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shift_date",
                    models.DateField(
                        default=datetime.date.today,
                        help_text="Date for this shift.",
                        verbose_name="Shift date",
                    ),
                ),
                (
                    "employee",
                    models.IntegerField(
                        default=0,
                        help_text="Employee (ID) responsible for this shift.",
                        verbose_name="Employee",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "license_plate",
                    models.CharField(
                        help_text="License plat for this vehicle",
                        max_length=255,
                        verbose_name="License plate",
                    ),
                ),
                (
                    "battery_level",
                    models.IntegerField(
                        default=100,
                        help_text="Battery level of this vehicle. Ranges 0 ~ 100.",
                        verbose_name="Battery level",
                    ),
                ),
                (
                    "in_use",
                    models.BooleanField(
                        default=False,
                        help_text="Represents if the vehicle is in use.",
                        verbose_name="In use",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[("Niu", "Niu"), ("Unknown", "Unknown")],
                        default="Unknown",
                        help_text="The brand model name of this vehicle.",
                        max_length=255,
                        verbose_name="Model",
                    ),
                ),
                (
                    "location_lat",
                    models.FloatField(
                        default=0,
                        help_text="Current location latitude.",
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "location_long",
                    models.FloatField(
                        default=0,
                        help_text="Current location longitude.",
                        verbose_name="Longitude",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShiftVehicle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        help_text="What order to visit vehicles for this shift.",
                        verbose_name="Order",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        help_text="Vehicle is assigned to this shift.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehicles.shift",
                        verbose_name="Shift",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        help_text="Vehicle is assigned to this shift.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehicles.vehicle",
                        verbose_name="Vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shift Vehicle Mapping",
                "verbose_name_plural": "Shift Vehicle Mappings",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="shift",
            name="vehicles",
            field=models.ManyToManyField(
                blank=True,
                help_text="Vehicles of this shift.",
                related_name="shifts",
                through="vehicles.ShiftVehicle",
                to="vehicles.vehicle",
                verbose_name="Vehicles",
            ),
        ),
    ]
