# Generated by Django 4.1.2 on 2022-10-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shiftvehicle",
            name="shift",
        ),
        migrations.RemoveField(
            model_name="shiftvehicle",
            name="vehicle",
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.DeleteModel(
            name="Shift",
        ),
        migrations.DeleteModel(
            name="ShiftVehicle",
        ),
    ]
